---

- name: Instalar apache2 Debian
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: true
  notify: Servicio apache2


- name: Servicio apache2
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
...
