---

- name: Instalar apache
  ansible.builtin.package:
    name: "{{ servicio }}"
    state: present
    update_cache: true
    

- name: Iniciar servicio
  ansible.builtin.service:
    name: "{{ servicio }}"
    state: started
    enabled: true

...
