---

- name: Incluir instalacion httpd CentOS
  ansible.builtin.include_tasks: centos.yml
  when: ansible_distribution == "CentOS"


- name: Incluir instalacion Debian
  ansible.builtin.include_tasks: debian.yml
  when: ansible_distribution == "Debian"

...
