---

- name: Instalar apache Rhel8
  ansible.builtin.yum:
    name: httpd
    state: present
    update_cache: true
  notify: Servicio httpd

- name: Servicio httpd
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true

- name: permitir trafico http
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled

...
