---

- name: Instalacion php
  ansible.builtin.include_tasks:
    file: php.yml


- name: Descargar, descomprimir Wordpress
  ansible.builtin.unarchive:
    src: "{{ version_wordpress }}"
    dest: /var/www/html/
    remote_src: true
    mode: '0775'
    owner: "{{ grupo_apache }}"
    group: "{{ grupo_apache }}"


- name: Configuracion wp-config
  ansible.builtin.include_tasks:
    file: wp-config.yml

...
