---

- name: Instalar php
  ansible.builtin.package:
    name: "{{ paquetes }}"
    state: present
    update_cache: true


- name: Reiniciar servicio httpd/apache
  ansible.builtin.service:
    name: "{{ servicio }}"
    state: restarted
  changed_when: false

...
