---

# Credenciales para la conexion de wordpress con postgresql
db_name: wordpress
db_user: wordpress
db_password: 123456

# Version de wordpress
version_wordpress: https://es.wordpress.org/latest-es_ES.tar.gz