---

- name: Instalar mysql
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - mysql-server
    - python3-pip

- name: instalar PyMySQL
  pip:
    name: PyMySQL
    state: present

- name: levantar servicio mysql
  service:
    name: mysqld
    state: started
    enabled: true

- name: crear db
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: crear usuario
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present

...
