---

- name: Incluir ficheros centos
  ansible.builtin.include_tasks: centos.yml
  when: ansible_distribution == "CentOS"


- name: Icluir ficheros debian
  ansible.builtin.include_tasks: debian.yml
  when: ansible_distribution == "Debian"

...