---

- name: Instalar mysql
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - mysql-server
    - python3-pip

- name: instalar PyMySQL
  pip:
    name: PyMySQL
    state: present

- name: levantar servicio mysql
  service:
    name: mysqld
    state: started
    enabled: true

- name: crear db
  mysql_db:
    name: wordpress
    state: present

- name: crear usuario
  mysql_user:
    name: wordpress
    password: 123456
    priv: wordpress.*:ALL
    state: present

...
